spring.application.name=Deadlines API

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/deadlines
spring.datasource.username=postgres
spring.datasource.password=CHANGEME

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.security.jwt.secret=amt2bWZrbXZta21wYXNwZHZtYVtwc2Rudmpkb2JuYjBhW3Nkdm5kZnVwWzxvaXNkdm5ib3c5ZXVwaXV2bmhiZnk4czk=
spring.security.jwt.access.expiration=10000
spring.security.jwt.refresh.expiration=604800

users.max-sessions=50
users.max-linked-accounts-per-messenger=2

outbox.batch-size=200
outbox.max-retries=5

minio.url=http://localhost:9000
minio.accessKey=ROOT
minio.secretKey=CHANGEME
minio.bucketNames=attachments

integration.telegram.bot-token=

spring.redis.hostname=localhost
spring.redis.port=6379

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.bootstrap-servers.producer.properties.spring.json.add.type.headers=false

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
